name: Deploy MultiDocker
on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Test react client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test image
        run: docker build -t ruinano/react-test -f ./client/Dockerfile.dev ./client
      - name: Run test
        run: docker run -e CI=true ruinano/react-test npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build clinet prod image
        run: docker build -t ruinano/multi-client ./client
      - name: Build nginx prod image
        run: docker build -t ruinano/multi-nginx ./nginx
      - name: Build server prod image
        run: docker build -t ruinano/multi-server ./server
      - name: Build worker prod image
        run: docker build -t ruinano/multi-worker ./worker
      - name: Push to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        run: docker push ruinano/multi-client
        run: docker push ruinano/multi-nginx 
        run: docker push ruinano/multi-server
        run: docker push ruinano/multi-worker