name: Deploy MultiDocker
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ruinano/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ruinano/react-test npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ruinano/multi-client ./client
      - run: docker build -t ruinano/multi-nginx ./nginx
      - run: docker build -t ruinano/multi-server ./server
      - run: docker build -t ruinano/multi-worker ./worker

      